config/routes.rb
Rails.application.routes.draw do

  
  root 'metrics#index'
  match '/metrics/rank', to: 'metrics#rank', via: :post
  match '/metrics/rate', to: 'metrics#rate', via: :post
  match '/weather', to: 'weather#index', via: :get
  match '/weather/search', to: 'weather#search', via: :get
  match '/weather/show', to: 'weather#show', via: :get
  match '/weather/filter', to: 'weather#filter', via: :get
  match '/metrics', to: 'metrics#index', via: :get
  resources :weather_locations
  resources :notifications
  
  resources :users
  
  match '/login', to: 'sessions#new', via: :get
  match '/login', to: 'sessions#request_password', via: :post
  match '/weather', to: 'sessions#update_password', via: :post
  match '/login_create', to: 'sessions#create', via: :post
  match '/logout', to: 'sessions#destroy', via: :delete
  match '/forgot_password', to: 'sessions#forgot_password', via: :get
  match '/change_password', to: 'sessions#change_password', via: :get

end

app/models/notification.rb
class Notification < ActiveRecord::Base
    belongs_to :user
    
    def self.send_notifications
        now = Time.now.utc
        notifications = Notification.where("time='"+now.hour.to_s+"'")
        notifications.each do|notification|
            user = User.find(notification.user_id)
            weather=[]
            cities = notification[:city_ids].split(',')
            sources = [user.source_1]
            if notification[:source]==CONSENSUS
                sources=[0,1,2]
            end
            cities.each do |city|
                city_weather={"city"=>GooglePlaces.get_city(city)}
                all=WeatherAPI.get_all_weather(GooglePlaces.get_coordinates(city),sources)
                if notification[:source]==CONSENSUS
                    raw_weather=all["consensus"]
                else
                    raw_weather=all["weather"][0]
                end
                if notification[:current]==1
                    city_weather["current"]=raw_weather["current"]
                end
                if notification[:daily]==1
                    city_weather["daily"]=raw_weather["daily"]
                end
                if notification[:hourly]==1
                    city_weather["hourly"]=raw_weather["hourly"]
                end
                weather.append(city_weather)
            end
            UserMailer.notification(user.email,weather).deliver
            #UserMailer.text_notification(user_cell, weather).deliver
        end
    end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
    before_filter :set_current_user
    
    def index
        if @current_user
            notifications = @current_user.notifications
            @notifications=[]
            notifications.each do |notification|
                cities_string=notification["city_names"]
                time = notification[:time]
                if time > 12
                    time = (time-12).to_s+" PM"
                else
                    time = time.to_s + " AM"
                end
                information=""
                if notification[:current]==1
                    information+="Current, "
                end
                if notification[:daily]==1
                    information+="Daily, "
                end
                if notification[:hourly]==1
                    information+="Hourly, "
                end
                sources = ""
                if notification[:source] == CONSENSUS
                    sources="Consensus"
                else
                    sources="Favorite Source"
                end
                @notifications.append({:id => notification[:id], "time"=>time,"cities"=>cities_string, "information"=>information, "sources"=>sources})
            end
            
        end
    end
    
    def new
        @cities = @current_user.weather_locations.flatten
    end
    
    def create
        cities = @current_user.weather_locations.flatten
        cities_string = ""
        city_names=""
        cities.each do |city|
            if params["cities"][city.city_id]=="1"
                cities_string+=city.city_id+","
                city_names+=city.city_name+"<br>"
            end
        end
        puts params
        time = params["time"].to_i
        if params["ampm"]=="PM"
            time+=12
        end
        @current_user.notifications.create(:city_ids =>cities_string, :city_names => city_names, :time =>time, :current =>params["information"]["current"],
        :daily =>params["information"]["daily"],:hourly =>params["information"]["hourly"],:source =>params["type"]["type"])
        redirect_to notifications_path
    end
    
    def destroy
        Notification.delete(params[:id])
        redirect_to notifications_path
    end
    
    def edit
       @cities = @current_user.weather_locations.flatten
       @notification = Notification.find(params[:id])
    end
    
    def update
        cities = @current_user.weather_locations.flatten
        cities_string = ""
        city_names=""
        cities.each do |city|
            if params["cities"][city.city_id]=="1"
                cities_string+=city.city_id+","
                city_names+=city.city_name+"<br>"
            end
        end
        puts params
        time = params["time"].to_i
        if params["ampm"]=="PM"
            time+=12
        end
        Notification.find(params[:id]).update_attributes(city_ids: cities_string, city_names: city_names, time: time, current: params["information"]["current"],
        daily: params["information"]["daily"],hourly: params["information"]["hourly"], source: params["type"]["type"])
        redirect_to notifications_path
         
    end
end

app/views/notifications/edit.html.haml
%h1 New Notification
= form_tag notification_path(@notification), method: :patch do
    %h2 Time
    %select{:name => "time"}
        -for i in 1..12
            -if @notification["time"]%12==i
                %option{:value => i, :selected => true}=i 
            - else
                %option{:value => i}=i
    %select{:name => "ampm"}
        %option{:value => "AM", :selected => @notification["time"]/12.to_f<=1} AM
        %option{:value => "PM", :selected => @notification["time"].to_f/12>1} PM
    %h2 Cities
    -@cities.each do |city|
        -checked = @notification["city_names"].split("<br>").include?(city.city_name)
        =check_box "cities", city.city_id.to_s, {:checked => checked}
        =city["city_name"]
        %br
    %h2 Information
    =check_box "information", "current", {:checked => @notification[:current]==1}
    Current
    =check_box "information", "daily", {:checked => @notification[:daily]==1}
    Daily
    =check_box "information", "hourly", {:checked => @notification[:hourly]==1}
    Hourly
    %h2 Source
    =radio_button "type", "type", 0, {:checked => @notification[:source]==0}
    Consensus
    =radio_button "type", "type",  1, {:checked => @notification[:source]==1}
    Favorite Source
    =submit_tag 'Save' 

app/views/notifications/index.html.haml
-if @current_user
    %h1 Your Notifications
    =button_to  'Create new Notification', new_notification_path, method: :get, :id => "create_notification_button"
    %table{:id => "notifications", :class => "container"}
        %thead
            %tr
                %th Time
                %th Cities
                %th Information
                %th Sources
                %th Edit
        %tbody
            -@notifications.each do |notification|
                %tr
                    %td=notification["time"]
                    %td=notification["cities"].html_safe
                    %td=notification["information"]
                    %td=notification["sources"]
                    %td.notes
                        =link_to 'Edit', edit_notification_path(notification)
                        =link_to 'Delete', notification_path(notification), method: :delete
-else
    %h2 Please log in to view notification settings.

app/views/notifications/new.html.haml
%h1 New Notification
= form_tag notifications_path, method: :post do
    %h2 Time
    %select{:name => "time"}
        -for i in 1..12
            %option{:value => i}=i
    %select{:name => "ampm"}
        %option{:value => "AM"} AM
        %option{:value => "PM"} PM
    UTC
    %h2 Cities
    -@cities.each do |city|
        =check_box "cities", city.city_id.to_s, {:checked => true}
        =city["city_name"]
        %br
    %h2 Information
    =check_box "information", "current"
    Current
    =check_box "information", "daily"
    Daily
    =check_box "information", "hourly"
    Hourly
    %h2 Source
    =radio_button "type", "type", 0
    Consensus
    =radio_button "type", "type",  1
    Favorite Source
    =submit_tag 'Create' 