config/routes.rb
Rails.application.routes.draw do

  
  root 'metrics#index'
  match '/metrics/rank', to: 'metrics#rank', via: :post
  match '/metrics/rate', to: 'metrics#rate', via: :post
  match '/weather', to: 'weather#index', via: :get
  match '/weather/search', to: 'weather#search', via: :get
  match '/weather/show', to: 'weather#show', via: :get
  match '/weather/filter', to: 'weather#filter', via: :get
  match '/metrics', to: 'metrics#index', via: :get
  resources :weather_locations
  resources :notifications
  
  resources :users
  
  match '/login', to: 'sessions#new', via: :get
  match '/login', to: 'sessions#request_password', via: :post
  match '/weather', to: 'sessions#update_password', via: :post
  match '/login_create', to: 'sessions#create', via: :post
  match '/logout', to: 'sessions#destroy', via: :delete
  match '/forgot_password', to: 'sessions#forgot_password', via: :get
  match '/change_password', to: 'sessions#change_password', via: :get

end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
    before_filter :set_current_user
    
    def index
        
    end
    
    def search
        @cities = GooglePlaces.get_places(params[:searched_city]['city_name'])
    end
    
    def show

        @owm = params[:source][:openweathermap]
        @ds = params[:source][:darksky]
        @wu = params[:source][:weatherunderground]
        
        sources = []
        @headings = []
        empty = true
        
        if params[:source][:darksky] == '1'
            sources.push( DARKSKY )
            @headings.push( "DarkSky" ) 
            empty = false;
        end
        
        if params[:source][:weatherunderground] == '1'
            sources.push( WEATHERUNDERGROUND )
            @headings.push( "WeatherUnderground" ) 
            empty = false
        end
        
        if params[:source][:openweathermap] == '1'
            sources.push( OPENWEATHERMAP ) 
            @headings.push( "OpenWeatherMap" ) 
            empty = false
        end
        
        
        if empty
            flash[:warning] = "No services selected; please select at least one service before searching."
            redirect_to weather_path
        else
            if @current_user
                sorted_sources=[]
                sorted_headings=[]
                if sources.index(@current_user.source_1)
                    sorted_sources.append(@current_user.source_1)
                    sorted_headings.append(SOURCENAMES[@current_user.source_1])
                end
                if sources.index(@current_user.source_2)
                    sorted_sources.append(@current_user.source_2)
                    sorted_headings.append(SOURCENAMES[@current_user.source_2])
                end
                if sources.index(@current_user.source_3)
                    sorted_sources.append(@current_user.source_3)
                    sorted_headings.append(SOURCENAMES[@current_user.source_3])
                end
                sources=sorted_sources
                @headings = sorted_headings
            end
            all=WeatherAPI.get_all_weather(GooglePlaces.get_coordinates(params[:city].keys[0]),sources)
            @weather= all["weather"]
            @consensus = all["consensus"]
            @city = params[:city][params[:city].keys[0]].keys[0]
            @id = params[:city].keys[0]
            @days=@weather[0]["daily"].keys
            @hours=@weather[0]["hourly"].keys
            @saved_location=false
            if @current_user && @current_user.weather_locations.find_by_city_id(@id)
                @saved_location=true
            end
        end
    end

    
    def self.consensus_class(consensus)
        if (consensus >= 75)
          return "good_consensus"
        else
          return "bad_consensus"
        end
    end
end

app/views/weather/index.html.haml
<link rel="stylesheet" type="app/assets/stylesheets" href="forms.css">

= form_tag weather_search_path, method: :get do

    = label :searched_city, :city_name, 'City: '
    = text_field :searched_city, 'city_name'
    = submit_tag 'Search'
  

app/views/weather/search.html.haml
= form_tag weather_search_path, method: :get do

    = label :searched_city, :city_name, 'City: '
    = text_field :searched_city, 'city_name'
    = submit_tag 'Search'
%br
= form_tag weather_show_path, method: :get do
    = check_box :source, 'openweathermap', :checked => true
    OpenWeatherMap 
    = check_box :source, 'darksky', :checked => true
    DarkSky
    = check_box :source, 'weatherunderground', :checked => true
    WeatherUnderground
    %br
    - @cities.each do |city|
        = submit_tag city[:name], :name=>'city['+city[:id]+']['+city[:name]+']'
        %br

app/views/weather/show.html.haml
- owmChecked = @owm == '1' ? true : false
- dsChecked = @ds == '1' ? true : false
- wuChecked = @wu == '1' ? true : false

= form_tag weather_search_path, method: :get do
    = label :searched_city, :city_name, 'City: '
    = text_field :searched_city, 'city_name'
    = submit_tag 'Search'
%br
= form_tag weather_show_path, method: :get do
    = check_box :source, 'openweathermap', :checked => owmChecked
    OpenWeatherMap 
    = check_box :source, 'darksky', :checked => dsChecked
    DarkSky 
    = check_box :source, 'weatherunderground', :checked => wuChecked
    WeatherUnderground 
    = submit_tag 'Refresh', :name=>'city['+@id.to_s+']['+@city.to_s+']'

-if @current_user&&!@saved_location
    = form_tag weather_locations_path+'?city_name='+@city+'&city_id='+@id, method: :post do
        = submit_tag 'Add to saved locations'
-elsif @current_user
    %h2 Location Saved

%h2 Current Weather for #@city
%table{:id => "currentWeather", :class => "container"}
    %thead
        %tr
            -@headings.each do |heading|
                %th=heading
            %th Consensus
    %tbody
        %tr
            - @weather.each do |source|
                %td 
                    =image_tag source["current"]["icon"]
                    %h3=source["current"]["temperature"].to_s + " °F"
                    %h4="Humidity: "+source["current"]["humidity"].to_s
                    %h4="Wind: "+source["current"]["wind"].to_s+" mph"
            %td 
                %h4{:class => WeatherController.consensus_class(@consensus["current"]["consensus"])}=@consensus["current"]["consensus"].to_s + "%"
                %h3=@consensus["current"]["temperature"].to_s + " °F"
                %h4="Humidity: "+@consensus["current"]["humidity"].to_s
                %h4="Wind: "+@consensus["current"]["wind"].to_s+" mph"
                    
%h2 Daily Forecast
%table{:id => "dailyWeather", :class => "container"}
    %thead
        %tr
            %th
            -@headings.each do |heading|
                %th=heading
            %th Consensus
    %tbody
        -@days.each do |day|
            %tr
                %td=day
                - @weather.each do |source|
                    %td 
                        %div.weather_main
                            =image_tag source["daily"][day]["icon"]
                            %p="H: "+source["daily"][day]["high"].to_s + " °F    L: "+source["daily"][day]["low"].to_s + " °F"
                        %div.weather_details
                            %p="Precipitation: "+source["daily"][day]["precipitation"].to_s + " in"
                            %p="Humidity: "+source["daily"][day]["humidity"].to_s
                            %p="Wind: "+source["daily"][day]["wind"].to_s+" mph"
                %td 
                    %div.weather_main
                        %h4{:class => WeatherController.consensus_class(@consensus["daily"][day]["consensus"])}=@consensus["daily"][day]["consensus"].to_s + "%"
                        %p="H: "+@consensus["daily"][day]["high"].to_s + " °F    L: "+@consensus["daily"][day]["low"].to_s + " °F"
                    %div.weather_details
                        %p="Precipitation: "+@consensus["daily"][day]["precipitation"].to_s + " in"
                        %p="Humidity: "+@consensus["daily"][day]["humidity"].to_s
                        %p="Wind: "+@consensus["daily"][day]["wind"].to_s+" mph"
                        
%h2= "Tri-hourly Forecast For Today"
%table{:id => "hourlyWeather", :class => "container"}
    %thead
        %tr
            %th
            -@headings.each do |heading|
                %th=heading
            %th Consensus
    %tbody
        -@hours.each do |hour|
            %tr
                %td=hour
                - @weather.each do |source|
                    %td 
                        %div.weather_main
                            =image_tag source["hourly"][hour]["icon"]
                            %p=source["hourly"][hour]["temperature"].to_s + " °F"
                        %div.weather_details
                            %p="Precipitation: "+source["hourly"][hour]["precipitation"].round(2).to_s + " in"
                            %p="Humidity: "+source["hourly"][hour]["humidity"].to_s
                            %p="Wind: "+source["hourly"][hour]["wind"].to_s+" mph"
                %td
                    %div.weather_main
                        %h4{:class => WeatherController.consensus_class(@consensus["hourly"][hour]["consensus"])}=@consensus["hourly"][hour]["consensus"].to_s + "%"
                        %p=@consensus["hourly"][hour]["temperature"].to_s + " °F"
                    %div.weather_details
                        %p="Precipitation: "+@consensus["hourly"][hour]["precipitation"].to_s + " in"
                        %p="Humidity: "+@consensus["hourly"][hour]["humidity"].to_s
                        %p="Wind: "+@consensus["hourly"][hour]["wind"].to_s+" mph"