config/routes.rb
Rails.application.routes.draw do

  
  root 'metrics#index'
  match '/metrics/rank', to: 'metrics#rank', via: :post
  match '/metrics/rate', to: 'metrics#rate', via: :post
  match '/weather', to: 'weather#index', via: :get
  match '/weather/search', to: 'weather#search', via: :get
  match '/weather/show', to: 'weather#show', via: :get
  match '/weather/filter', to: 'weather#filter', via: :get
  match '/metrics', to: 'metrics#index', via: :get
  resources :weather_locations
  resources :notifications
  
  resources :users
  
  match '/login', to: 'sessions#new', via: :get
  match '/login', to: 'sessions#request_password', via: :post
  match '/weather', to: 'sessions#update_password', via: :post
  match '/login_create', to: 'sessions#create', via: :post
  match '/logout', to: 'sessions#destroy', via: :delete
  match '/forgot_password', to: 'sessions#forgot_password', via: :get
  match '/change_password', to: 'sessions#change_password', via: :get

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Weather Dashboard
    = stylesheet_link_tag 'application', 'media' => 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

    %div.header
      %h1.title Weather Dashboard
    %ul
      %li
        =link_to("Metrics", metrics_path,:class=>ApplicationController.link_class("metrics"))
        =link_to("Search Weather", weather_path,:class=>ApplicationController.link_class("weather"))
        =link_to("My Weather", weather_locations_path,:class=>ApplicationController.link_class("weather_locations"))
        =link_to("Notifications", notifications_path,:class=>ApplicationController.link_class("notifications"))
      
        -if !@current_user
          = link_to 'Login', login_path, method: :get, :id => 'signupLogin'
        -else
          = link_to 'Change Password', change_password_path, method: :get, :id => 'change_pwd'
          = link_to 'Log Out', logout_path, method: :delete, :id => 'logout'

    
    
    #main
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]

    = yield